spring:
  datasource:
    username: root
    password: 121800
    url: jdbc:mysql://localhost:3306/jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    type: org.springframework.jdbc.datasource.DriverManagerDataSource